assembly=$1

echo "4 - Compare and clusterize the samples from the .bam files using deeptools"
bamFiles=$(ls -1 ./c*H2*Rep*${assembly}*/c*sorted_dedup*.bam | grep "SUMO\|NO")
names=$(ls -1 ./c*H2*Rep*${assembly}*/c*sorted_dedup*.bam | grep "SUMO\|NO" | sed -e"s/_all_dm6//g" -e "s/sorted_dedup.//g" -e "s,/, ,g" -e "s/cnr_//g" | awk '{print $2}')
echo $bamFiles
echo $names

conda run -n deeptools multiBamSummary bins --bamfiles ${bamFiles} --minMappingQuality 30 -out readCounts_bamfiles.npz --labels ${names} --outRawCounts readCounts_bamfiles.tab -v
# --bamfiles FILE1 FILE2 [FILE1 FILE2 ...], -b FILE1 FILE2 [FILE1 FILE2 ...]
#            List of indexed bam files separated by spaces.
#            (default: None)
# --minMappingQuality INT
#                     If set, only reads that have a mapping quality score
#                     of at least this are considered. (default: None)
# --outFileName OUTFILENAME, -out OUTFILENAME, -o OUTFILENAME
#               File name to save the coverage matrix. This matrix can
#               be subsequently plotted using plotCorrelation or or
#               plotPCA. (default: None)
# --outFileName OUTFILENAME, -out OUTFILENAME, -o OUTFILENAME
#               File name to save the coverage matrix. This matrix can
#               be subsequently plotted using plotCorrelation or or
#               plotPCA. (default: None)
# --verbose, -v         Set to see processing messages. (default: False)

conda run -n deeptools plotCorrelation --corData readCounts_bamfiles.npz --corMethod spearman --skipZeros --plotTitle "Spearman Correlation of ChIPseq samples" --whatToPlot heatmap --colorMap bwr --plotNumbers --plotFile heatmap_bamfiles.pdf --outFileCorMatrix SpearmanCorr_readCounts_bamfiles.tsv
# Tool for the analysis and visualization of sample correlations based on the output of multiBamSummary or
# multiBigwigSummary. Pearson or Spearman methods are available to compute correlation
# coefficients. Results can be saved as multiple
# scatter plots depicting the pairwise correlations or as a clustered heatmap,
# where the colors represent the correlation coefficients and the clusters are constructed using complete linkage.
# Optionally, the values can be saved as tables, too.
# --corData FILE, -in FILE
#                     Compressed matrix of values generated by
#                     multiBigwigSummary or multiBamSummary
# --corMethod {spearman,pearson}, -c {spearman,pearson}
#             Correlation method.
# --skipZeros           By setting this option, genomic regions that have zero
#                        or missing (nan) values in all samples are excluded.
# --plotTitle PLOTTITLE, -T PLOTTITLE
#             Title of the plot, to be printed on top of the
#             generated image. Leave blank for no title. (Default: )
# --whatToPlot {heatmap,scatterplot}, -p {heatmap,scatterplot}
#              Choose between a heatmap or pairwise scatter plots
# --colorMap            Color map to use for the heatmap. Available values can
#                       be seen here: http://matplotlib.org/examples/color/col
#                       ormaps_reference.html
# --plotNumbers         If set, then the correlation number is plotted on top
#                       of the heatmap. This option is only valid when
#                       plotting a heatmap.
# --plotFile FILE, -o FILE
#            File to save the heatmap to. The file extension
#            determines the format, so heatmap.pdf will save the
#            heatmap in PDF format. The available formats are:
#           .png, .eps, .pdf and .svg.
# --outFileCorMatrix FILE
#                    Save matrix with pairwise correlation values to a tab-
#                    separated file.


